// swift-tools-version: 6.2
import PackageDescription

let packageDir = Context.packageDirectory

let package = Package(
    name: "WasmClient",
    platforms: [
        .iOS(.v17),
    ],
    products: [
        .library(name: "WasmClient", targets: ["WasmClient"]),
        .library(name: "WasmClientLive", targets: ["WasmClientLive"]),
    ],
    dependencies: [
        .package(
            url: "https://github.com/pointfreeco/swift-composable-architecture.git",
            branch: "main"
        ),
        .package(
            url: "https://github.com/apple/swift-protobuf.git",
            branch: "main"
        ),
        .package(
            url: "https://github.com/mahainc/flow-kit.git",
            from: "1.2.3"
        ),
    ],
    targets: [
        .target(
            name: "WasmClient",
            dependencies: [
                .product(name: "ComposableArchitecture", package: "swift-composable-architecture"),
            ]
        ),
        .target(
            name: "WasmClientLive",
            dependencies: [
                .product(name: "ComposableArchitecture", package: "swift-composable-architecture"),
                .product(name: "SwiftProtobuf", package: "swift-protobuf"),
                .product(name: "FlowKit", package: "flow-kit"),
                .product(name: "FlowKitCModules", package: "flow-kit"),
                "WasmClient",
            ],
            swiftSettings: [
                // Merged modules directory containing symlinks to swiftmodule files
                // from both ios-arm64 (device) and ios-arm64_x86_64-simulator slices.
                // This lets the compiler find FlowKit's re-exported sub-modules
                // (AsyncWasm, TaskWasm, etc.) for any destination.
                // Generated by: scripts/merge-flowkit-modules.sh
                .unsafeFlags([
                    "-I", "\(packageDir)/.build/flowkit-merged-modules",
                ]),
            ]
        ),
    ]
)
